### ISSUE TITLE
Bagil isn't saving the discord config

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#452] opened 2017-12-09 16:49 UTC
I have added the admin discord channel config for bagil multiple times now, and it hasn't been taking...

works fine on sybil and terry

**Comment by Cyberboss** [comment] 2017-12-09 23:14
Weird bug relating to the chat page not initializing on CP load

**Comment by Cyberboss** [comment] 2017-12-12 20:35
Unable to repro, probably generic CP shittiness. Gonna close this a a duplicate of #421.

**Comment by Cyberboss** [comment] 2017-12-12 20:35
Duplicate of #421

**Closed by Cyberboss** 2017-12-12 20:35 UTC
Labels: Backlog, Bug
