### ISSUE TITLE
use app.UsePathBase to fix subfolder proxy redirects

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#1775] opened 2024-01-20 17:46 UTC
use app.UsePathBase with the path config to fix subfolder proxy redirects.

this is what is blocking getting campbell on tgs6

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0#work-with-path-base-and-proxies-that-change-the-request-path

**Comment by Cyberboss** [comment] 2024-01-20 20:51
Duplicate of #1761. Will see if I can get it done this weekend

**Closed by Cyberboss** 2024-01-20 20:51 UTC
Labels: Bug, Reproduction Required

**Comment by Cyberboss** [comment] 2024-01-20 20:55
The main issue is the fix breaks the webpanel and I need to find out why
