### ISSUE TITLE
ahelps aren't relaying through discord

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation-server#100] opened 2017-07-03 20:06 UTC
Server starts and shutdowns are relaying fine, but ahelp related messages aren't being sent.

**Comment by MrStonedOne** [comment] 2017-07-03 22:29
https://github.com/tgstation/byond-server

**Comment by Cyberboss** [comment] 2017-07-04 18:19
@LetterJay did you assign an admin channel?

**Comment by Cyberboss** [comment] 2017-07-05 17:55
Nvm, dupe of #104

**Closed by Cyberboss** 2017-07-05 17:55 UTC
